query questionOfToday {
  activeDailyCodingChallengeQuestion {
    question {
      acRate
      difficulty
      questionId: questionFrontendId
      title
      titleSlug
      topicTags {
        name
      }
    }
  }
}